//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dataaccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class dependencytable
    {
        public int userid { get; set; }
        public string userfirstname { get; set; }
        public string userlastname { get; set; }
        public string useraddress { get; set; }
        public string useremail { get; set; }
    }
}
